---
- name: "installing nodejs_14.x"
  shell:
    cmd: curl -sL https://deb.nodesource.com/setup_14.x | bash
    creates: /usr/bin/npm
  become: true
  become_method: sudo

- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - ffuf
      - dnsrecon
      - feroxbuster
      - fonts-noto-color-emoji
      - fonts-cascadia-code
      - libqt5sensors5
      - libqt5webkit5
      - snmp
      - tnscmd10g
      - npm
      - wkhtmltopdf
      - azure-cli
      - enum4linux
      - redis-tools
      - smbmap
      - nbtscan
      - nikto
      - snmp
      - sslscan
      - exploitdb
      - anonsurf
      - anonsurf-gtk
      - anonsurf-cli
      - seclists      
    state: latest
  become: true
  become_method: sudo
