---
- name: register status of gophish
  stat:
    path: /opt/gophish/gophish
  register: gophish

- name: Install and configure Gophish
  block:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
      register: build_dir  
    - name: "Copying python script to download github releases"
      copy:
        src: "files/githubdownload.py"
        dest: "{{ build_dir.path }}/githubdownload.py"
        owner: root
        group: root
        mode: 0755

    - name: "Downloading github releases"
      shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
      loop:
        - { repo: "gophish/gophish", regex: "linux-64bit.zip", location: "/opt/gophish" }
      async: 45
      poll: 0

    - name: Remove temporary build directory
      ansible.builtin.file:
        path: "{{ build_dir.path }}"
        state: absent
      when: build_dir.path is defined

    - name: Set executable permissions
      ansible.builtin.file:
        path: /opt/gophish/gophish
        mode: "u+x"
  when: "not gophish.stat.exists"
  become: true
  become_method: sudo