# code: language=ansible
---
- name: "Cloning bulk-extractor repo"
  git:
    repo: https://github.com/simsong/bulk_extractor.git
    dest: /opt/bulk_extractor
    recursive: true
  become: true
  become_method: ansible.builtin.sudo

- name: Build bulk-extractor
  command:
    cmd: "{{ item.cmd }}"
    chdir: "{{ item.chdir }}"
    creates: /usr/local/bin/bulk_extractor
  loop:
    - { cmd: "sh bootstrap.sh", chdir: /opt/bulk_extractor }
    - { cmd: "./configure", chdir: /opt/bulk_extractor }
    - { cmd: "make", chdir: /opt/bulk_extractor }
    - { cmd: "make install", chdir: /opt/bulk_extractor }
  become: true
  become_method: ansible.builtin.sudo
